### ISSUE TITLE
Sample Stream with twitter.Entities nil

### ISSUE THREAD

**Issue by XescuGC** [dghubble/go-twitter#28]
Some times the object `Tweet` has the attribute `Entities` nil `(*twitter.Entities)(nil)` instead of the corresponding struct, I've tried to debug it but for what I've seen the JSON that twitter sends is correct but somehow when the struct is constructed the `Entities` are not.

I don't know if this is the way it should work, because sometimes it works correctly with a tweet that has no entities in the JSON and build the correct struct with the attributes by default. Right now I can evade the error (because I was iterating over the `Urls`) by checking if Entities is nil.

I would like to help more, so I'll try to find why it happens if it's not the expected behavior, but it may be easy for you haha.

To try this just run the `stream.Sample` and check for the `Entities` to be nil (or access some of the attributes of the Entities struct, in which case a panic will rise) you have to let it run for a while.

**Comment by dghubble** [comment]
You should always be checking if the Tweet `Entities` field is nil before dereferencing the pointer. Go standard library `encoding/json` Unmarshal rules determine whether a struct is allocated. If no entities are returned by the API, nil is expected. Can you gather more info about the case you get an empty struct? I'd guess there is a whitespace or some subtle field causing the allocation, which would be expected then.

**Comment by XescuGC** [comment]
So if the Tweet Entities are all empty then it's expected to be nil instead of a Entities struct? For what I've seen so far some tweets with entities in the JSON part are constructed without it. I'll try to debug it more so I can give you more information :). I'm a bit newbie in go hehe.

**Comment by XescuGC** [comment]
I've debugged a little more and added a test that inflates a tweet and don't sets the twitter.Entities, if it's correct I can PR it, but for now it's here: https://github.com/XescuGC/go-twitter/commit/29fb0ef59c9c6e8538a469e9cb0062be2fd32bcf . I've token one of the JSONs from TwitterStream that make the Entity be nil. Is that test correct?

**Comment by dghubble** [comment]
Thanks for the test case, it was helpful. Digging into this revealed it has little for do with `Tweet.Entities` decoding. Lookup the Tweet Id through the REST API and there is a decoding problem:

```
json: cannot unmarshal number into Go value of type twitter.Contributor
```

Twitter [documents](https://dev.twitter.com/overview/api/tweets#obj-contributors) what the "contributors" field should look like 

```
"contributors":
[
    {
        "id":819797,
        "id_str":"819797",
        "screen_name":"episod"
    }
]
```

and go-twitter matches that:

```
// Contributor represents a brief summary of a User identifiers.
type Contributor struct {
	ID         int64  `json:"id"`
	IDStr      string `json:"id_str"`
	ScreenName string `json:"screen_name"`
}
```

If we look at the actual response the API sends (which you included), that's not what is received:

```
"contributors": [
    3162711857
],
```

I imagine this is a documentation issue on Twitter's side so `go-login` can remove `contributors` decoding for now or assume a `[]int64` is the new "contributors" format.

This is hard to notice. First, few Tweets actually have contributors data attached to them, so most decode just fine.

In the streaming API usage, this particular Tweet struct is missing multiple fields because the Tweet is only partially decoded into the struct. This would be apparent via the REST API which surfaces such errors, but the streaming API swallows decoder errors and presents a stream of best-effort [Messages](https://github.com/dghubble/go-twitter#receiving-messages). To prevent something like this in future, I'd need to design a way to give channels of messages and errors, but avoid cluttering up clients' code.

Thanks!

> So if the Tweet Entities are all empty then it's expected to be nil instead of a Entities struct?

Yes

**Comment by dghubble** [comment]
For now, I'm going to remove "contributors" from Tweets. The field breaks Tweet parsing in streams if the format is inconsistent across APIs.

**Comment by vpolouchkine** [comment]
I'm back in the office on 11/07 and will investigate this. Thanks @dghubble.

**Comment by vpolouchkine** [comment]
Hey @dghubble, I did some internal spelunking and can confirm that `contributors` is a deprecated field for an inactive feature. I think it's fine to ignore it.

**Comment by dghubble** [comment]
Thanks!
