### ISSUE TITLE
twitter rate limit handling

### ISSUE THREAD

**Issue by dougnukem** [dghubble/go-twitter#8]
## Overview

It would be a useful option for a twitter API client to support handling of API rate limits:
- [Twitter API Rate Limiting](https://dev.twitter.com/rest/public/rate-limiting)
- [Rate Limit Table](https://dev.twitter.com/rest/public/rate-limits)

Rate limits can be returned by the Twitter API when calling specific REST endpoints as HTTP headers:

From the docs:

> Note that the HTTP headers are contextual. When using app-only auth, they indicate the rate limit for the application context. When using user-based auth, they indicate the rate limit for that user-application context.
> - X-Rate-Limit-Limit: the rate limit ceiling for that given request
> - X-Rate-Limit-Remaining: the number of requests left for the 15 minute window
> - X-Rate-Limit-Reset: the remaining window before the rate limit resets in UTC epoch seconds
>   When an application exceeds the rate limit for a given API endpoint, the Twitter API will now return an HTTP 429 “Too Many Requests” response code.
> 
> If you hit the rate limit on a given endpoint, this is the body of the HTTP 429 message that you will see:
> 
> `{ "errors": [ { "code": 88, "message": "Rate limit exceeded" } ] }`

The client can also request their current rate limits across all endpoints:
- [application/rate_limit_status](https://dev.twitter.com/rest/reference/get/application/rate_limit_status)

```
{
  "rate_limit_context": {
    "access_token": "786491-24zE39NUezJ8UTmOGOtLhgyLgCkPyY4dAcx6NA6sDKw"
  },
  "resources": {
    "users": {
      "/users/profile_banner": {
        "limit": 180,
        "remaining": 180,
        "reset": 1403602426
      },
      "/users/suggestions/:slug/members": {
        "limit": 15,
        "remaining": 15,
        "reset": 1403602426
      },
...
```
## Proposed Opt-In Rate Limiting

We should avoid complicating the `go-twitter` library with optional rate limit functionality, but allow users to configure or opt-in if they want to utilize it.
### Default Behavior

The default `go-twitter` behavior should be to ignore rate limit headers and not add the complexity to the internals if possible.
### Rate Limit opt-in

If the user opts in to using rate limiting they should be able to enable it as simply as:

```
    // Twitter client
    client := twitter.NewClient(httpClient)
    client.EnableRateLimitBlocking()
```
### Implementation

**Rate Limit Policies**
- **default** `NoOpRateLimit` - default behavior doesn't limit the client when calling the API (maybe this is just having a nil rate limit implementation that we detect)
- `ErrorRateLimit` - we track API rate limits on client per endpoint and if we're at the limit the API call returns an error (but avoids hitting the remote Twitter API service and thus avoiding being blacklisted etc)
- `BlockingRateLimit` - we keep track of API rate limits per endpoint and when a call is made that would exceed it we block the call and wait until the rate limit is reset (this could be up to 15 minutes if rate limits are reached quickly in a given time period)
- `TimeoutRateLimit(duration)` - we could provide a timeout duration that we would block and wait if we're at a rate limit if we timeout it returns an error

**Rate Limiter**

There is a generic rate limiter library that could be useful:
- https://github.com/ulule/limiter

It would allow us to configure a simple in-memory concurrent access cache of current API rate limits.

```
    client := twitter.NewClient(httpClient)

    // in-memory store with a goroutine which clears expired keys every 30 seconds
    store := limiter.NewMemoryStore("prefix_for_keys", 30*time.Second)
    client.EnableRateLimitBlocking(store)
```

As a bonus `limiter.Limiter` can be backed by a redis store so it could allow for distributed rate limit tracking on a cluster of servers using the twitter library.

```
    client := twitter.NewClient(httpClient)

    // Create a Redis pool.
    pool := redis.NewPool(func() (redis.Conn, error) {
        c, err := redis.Dial("tcp", ":6379")
        if err != nil {
            return nil, err
        }
        return c, err
    }, 100)

    // Create a store with the pool.
    store, err := limiter.NewRedisStoreWithOptions(
        pool,
        limiter.StoreOptions{Prefix: "go-twitter", MaxRetry: 3})

    if err != nil {
        return err
    }
    client.EnableRateLimitBlocking(store)
```
### RateLimiter Service Usage

```
type Limiter interface {
  // Get retrieves the Limit state indicating we should decrement current Limit.remaining
  Get() (*Limit, error)
  // Limit retrieves the latest Limit state or nil if we have none (useful for monitoring and debugging)
  Limit() *Limit
}

type RateLimiter struct {
    Statuses struct {
        UserTimeline Limiter
    }
}
```

Then in the serivces we could just call:

```
func (s *TimelineService) UserTimeline(params *UserTimelineParams) ([]Tweet, *http.Response, error) {
    tweets := new([]Tweet)
    apiError := new(APIError)
    var err error

    if s.RateLimiter {
        _, err = s.RateLimiter.Statuses.UserTimeline.Get()
    }

    if err == nil {
        resp, err := s.sling.New().Get("user_timeline.json").QueryStruct(params).Receive(tweets, apiError)
    }

    return *tweets, resp, relevantError(err, *apiError)
}
```

**Comment by dougnukem** [comment]
It'd be nice if there was some way to intercept or filter any http api call then we could map the rate limits to the REST URL paths.

Maybe we can wrap or decorate the http.Client and have it return an error early before it makes the call?

**Comment by dougnukem** [comment]
It seems like we could do something with providing our own `http.Transport` to filter and provide rate limit logic there, maybe something similiar to this:
- https://github.com/mmcloughlin/ghr/blob/0a008d3cb57649c35a574d26eaace5f9b6f3a2d0/ratelimitedtransport.go

```go

// RateLimitedTransport is used to conform to rate limits that are
// communicated through "X-RateLimit-" headers, like GitHub's API. It
// implements http.RoundTripper and can be used for configuring a http.Client.
type RateLimitedTransport struct {
	Base http.RoundTripper
}

func (t *RateLimitedTransport) RoundTrip(req *http.Request) (*http.Response, error) {
	res, err := t.base().RoundTrip(req)
	if err != nil {
		return res, err
	}

	// Fetch headers
	remStr := res.Header.Get("X-RateLimit-Remaining")
	if remStr == "" {
		return res, err
	}
	resetStr := res.Header.Get("X-RateLimit-Reset")
	if resetStr == "" {
		return res, err
	}

	rem, err := strconv.Atoi(remStr)
	if err != nil {
		return res, err
	}
	epoch, err := strconv.ParseInt(resetStr, 10, 64)
	if err != nil {
		return res, err
	}
	reset := time.Unix(epoch, 0)

	// Determine sleep time
	untilReset := reset.Sub(time.Now())
	delay := time.Duration(float64(untilReset) / (float64(rem) + 1))
	time.Sleep(delay)

	return res, err
}
```

This shows how we could receive rate limit responses and act on them but maybe we could apply limiter policy and decide to stop the request from being sent in the first place?

**Comment by dghubble** [comment]
First, thanks for your detailed thoughts around this. I really appreciate it.

For simple cases, the Twitter rate limit headers can be read directly from the `http.Response` and callers can use those values to make a decision about whether to retry.

    homeTimelineParams := &twitter.HomeTimelineParams{Count: 2}
    tweets, resp, err := client.Timelines.HomeTimeline(homeTimelineParams)

    // window before rate limit resets
    resp.Header.Get("X-Rate-Limit-Reset")
    // requests remaining for the endpoint, user context, and 15 min. window
    resp.Header.Get("X-Rate-Limit-Remaining")
    // rate limit ceiling
    resp.Header.Get("X-Rate-Limit-Limit")

This is one of the reasons endpoints return the actual `http.Response` along with the desired Twitter struct (`google/go-github` returns this as well).

A more complete solution ideally shouldn't require many changes to `go-twitter`. Rate limiting is common to all APIs, just like authentication, retrying, and dial or connection timeouts. It is something I prefer be handled by the `http.Client` that is passed in. More specifically, by the client's chain of `http.Transport`s, closer to your last suggestion.

That nicely leaves the `go-twitter` API Client responsible for the Twitter-specific stuff, like marshalling parameters and decoding JSON responses.

`go-twitter` accepts an `http.Client` to let users customize client behavior, modify timeouts, create multiple Twitter clients auth'd as different users (or a mixture of app auth and user auth), and simplifies `go-twitter` testing and downstream testing. Authentication packages like [dghubble/oauth1](https://github.com/dghubble/oauth1) and [golang.org/x/oauth2](https://godoc.org/golang.org/x/oauth2) both use the `http.Transport` approach as well.

I prefer to avoid methods like these:

    client := twitter.NewClient(httpClient)
    client.SetConsumerKey(xx)
    client.EnableRateLimiting()
    client.SetDelay(2*time.Second)

The first would mean `go-twitter` decides what auth library is used. The second would mean `go-twitter` decides what rate limiting library is used. The third would mean `go-twitter` is so coupled to its rate limiting approach that a sleep time has to be exposed on the API. What happens when a user wants to be notified to programmatically handle a limit being hit? Maybe the user wants to mine some bitcoin instead of sleeping, etc. - point is, I'd prefer control over request scoped matters stay with the client if at all possible.

Anaconda in particular is guilty of all of the above and uses a single global auth context as well - its an example of a design I'd like to steer clear of (no offense to those authors).

I think your last approach is the more promsing way to explore to do this well. Apologies for the delay in replying to your thoughts on this. I might have some time to explore approaches to this in upcoming weekends.

**Comment by dghubble** [comment]
Valuable discussion, but I'm closing since there hasn't been progress on this.
